import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createServer, type Server } from 'node:http';
import { createApp } from '../src/app.js';
import { applyLocalFilePlan, localFileSnapshot } from '../src/file-manager.js';
import { assetHash, loadWorkspaceConfig, planFileChange } from '@mygitnotes/core';
let root: string, server: Server, base: string;
const git = (...args: string[]) => execFileSync('git', args, { cwd: root, stdio: 'pipe' });
const write = (file: string, content: string | Buffer) => {
  fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
  fs.writeFileSync(path.join(root, file), content);
};
beforeEach(async () => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'mygitnotes-files-'));
  vi.stubEnv('MYGITNOTES_SOURCE', 'local');
  vi.stubEnv('MYGITNOTES_LOCAL_PATH', root);
  vi.stubEnv('VERCEL', '');
  vi.stubEnv('APP_URL', '');
  git('init', '-b', 'main');
  git('config', 'user.name', 'Test');
  git('config', 'user.email', 'test@example.com');
  write('.github-notes.yaml', 'schema_version: 1\nworkspace:\n  title: Test\n  default_notebook: a\nnotebooks:\n  - id: a\n    title: A\n    root: notes/a\n  - id: b\n    title: B\n    root: notes/b\n');
  write('notes/a/one/note.md', '# Note\n');
  write('notes/a/two/_dir.yml', 'title: Two\n');
  write('notes/a/.hidden.json', '{"a":1}\n');
  write('notes/b/other.md', '# Other');
  write('notes/a/one/image.png', Buffer.from([137, 80, 78, 71, 0, 255]));
  git('add', '.');
  git('commit', '-m', 'fixture');
  server = createServer(createApp(root));
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  base = `http://127.0.0.1:${(server.address() as any).port}`;
});
afterEach(async () => {
  if (server) await new Promise<void>(resolve => server.close(() => resolve()));
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  if (root) fs.rmSync(root, { recursive: true, force: true });
});
const list = () => fetch(base + '/api/files?notebookId=a').then(r => r.json());
const post = async (command: Record<string, unknown>, revision?: string) => fetch(base + '/api/files', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command: { notebookId: 'a', ...command }, revision: revision || (await list()).revision }) });

it('lists notebook files including hidden entries, reads raw text, creates and saves empty files', async () => {
  const listing = await list();
  expect(listing.entries.some((e: any) => e.path === 'notes/a/.hidden.json' && e.hidden)).toBe(true);
  expect(listing.entries.some((e: any) => e.path.startsWith('notes/b'))).toBe(false);
  expect((await post({ kind: 'create', path: 'notes/a/new.json' })).status).toBe(200);
  expect(fs.statSync(path.join(root, 'notes/a/new.json')).size).toBe(0);
  expect((await post({ kind: 'write', path: 'notes/a/new.json', content: '{"saved":true}\r\n' })).status).toBe(200);
  const read = await fetch(base + '/api/files/read?notebookId=a&path=notes/a/new.json').then(r => r.json());
  expect(read.content).toBe('{"saved":true}\r\n');
  expect(git('log', '--format=%s').toString().trim()).toBe('fixture');
});
it('moves binary files with a directory, preserves hash URLs, uploads and deletes', async () => {
  const original = fs.readFileSync(path.join(root, 'notes/a/one/image.png'));
  expect((await post({ kind: 'move', path: 'notes/a/one', destination: 'notes/a/two/one' })).status).toBe(200);
  const response = await fetch(base + '/raw-assets/by-hash/' + assetHash(original));
  expect(Buffer.from(await response.arrayBuffer())).toEqual(original);
  expect(response.headers.get('content-security-policy')).toContain('sandbox');
  expect((await post({ kind: 'upload', path: 'notes/a/upload.bin', base64: original.toString('base64') })).status).toBe(200);
  expect(fs.readFileSync(path.join(root, 'notes/a/upload.bin'))).toEqual(original);
  expect((await post({ kind: 'delete', path: 'notes/a/upload.bin' })).status).toBe(200);
  expect(fs.existsSync(path.join(root, 'notes/a/upload.bin'))).toBe(false);
});
it('rejects stale revisions, cross-notebook paths, symlinks, overwrite and read-only writes', async () => {
  const before = await list();
  write('notes/a/newer.txt', 'new');
  expect((await post({ kind: 'write', path: 'notes/a/.hidden.json', content: 'old' }, before.revision)).status).toBe(409);
  expect(fs.readFileSync(path.join(root, 'notes/a/.hidden.json'), 'utf8')).toContain('"a":1');
  expect((await post({ kind: 'create', path: 'notes/b/new.txt' })).status).toBe(400);
  expect((await post({ kind: 'create', path: 'notes/a/.hidden.json' })).status).toBe(400);
  fs.symlinkSync(path.join(root, 'notes/b'), path.join(root, 'notes/a/link'));
  expect((await post({ kind: 'create', path: 'notes/a/link/new.txt' })).status).toBe(400);
  expect((await fetch(base + '/api/files/read?notebookId=a&path=notes/b/other.md')).status).toBe(403);
  git('checkout', '-b', 'core');
  expect((await list()).writable).toBe(false);
  expect((await post({ kind: 'create', path: 'notes/a/no.txt' })).status).toBe(403);
});
it('restores the original binary and text snapshot after a write fails', () => {
  const before = localFileSnapshot(root, loadWorkspaceConfig(root)!.notebooks), after = planFileChange(before, { kind: 'move', notebookId: 'a', path: 'notes/a/one', destination: 'notes/a/two/one' });
  const rename = fs.renameSync.bind(fs);
  let calls = 0;
  vi.spyOn(fs, 'renameSync').mockImplementation((...args) => {
    if (++calls === 2) throw new Error('Injected failure');
    return rename(...args);
  });
  expect(() => applyLocalFilePlan(root, before, after)).toThrow('Injected failure');
  expect(localFileSnapshot(root, loadWorkspaceConfig(root)!.notebooks)).toEqual(before);
});
it('preserves folder contents or deletes the entire tree and reports deleted directories for selection repair', async () => {
  write('notes/a/one/child/.hidden.txt', 'keep hidden');
  write('notes/a/one/_dir.yml', 'title: One\n');
  const bytes = fs.readFileSync(path.join(root, 'notes/a/one/image.png'));
  const preserved = await post({ kind: 'remove-directory', path: 'notes/a/one', destination: 'notes/a/two' });
  expect(preserved.status).toBe(200);
  expect((await preserved.json()).pathMap['notes/a/one/child']).toBe('notes/a/two/child');
  expect(fs.readFileSync(path.join(root, 'notes/a/two/image.png'))).toEqual(bytes);
  expect(fs.readFileSync(path.join(root, 'notes/a/two/child/.hidden.txt'), 'utf8')).toBe('keep hidden');
  expect(fs.readFileSync(path.join(root, 'notes/a/two/_dir.yml'), 'utf8')).toBe('title: Two\n');
  const deleted = await post({ kind: 'delete-directory', path: 'notes/a/two' });
  expect(deleted.status).toBe(200);
  expect(await deleted.json()).toMatchObject({ selectedPath: 'notes/a', pathMap: {}, deletedPaths: expect.arrayContaining(['notes/a/two', 'notes/a/two/child', 'notes/a/two/child/.hidden.txt', 'notes/a/two/image.png', 'notes/a/two/note.md', 'notes/a/two/_dir.yml']) });
  expect(fs.existsSync(path.join(root, 'notes/a/two'))).toBe(false);
  expect(fs.readFileSync(path.join(root, 'notes/b/other.md'), 'utf8')).toBe('# Other');
});
it('rejects old catalog deletion and stale metadata edits after independent directory reads', async () => {
  const initial = await list();
  write('notes/a/one/new.md', '# Not in the initial scope\n');
  const metadata = await fetch(base + '/api/files/read?notebookId=a&path=notes/a/one').then(response => response.json());
  expect(metadata.revision).not.toBe(initial.revision);
  write('notes/a/one/_dir.yml', 'title: External metadata\n');
  expect((await post({ kind: 'metadata', path: 'notes/a/one', title: 'Stale edit', description: '', order: 0 }, metadata.revision)).status).toBe(409);
  expect(fs.readFileSync(path.join(root, 'notes/a/one/_dir.yml'), 'utf8')).toBe('title: External metadata\n');
  expect((await post({ kind: 'delete-directory', path: 'notes/a/one' }, initial.revision)).status).toBe(409);
  expect(fs.readFileSync(path.join(root, 'notes/a/one/new.md'), 'utf8')).toBe('# Not in the initial scope\n');
  const refreshed = await list();
  expect(refreshed.entries).toEqual(expect.arrayContaining([expect.objectContaining({ path: 'notes/a/one/new.md' })]));
  expect((await post({ kind: 'delete-directory', path: 'notes/a/one' }, refreshed.revision)).status).toBe(200);
  expect(fs.existsSync(path.join(root, 'notes/a/one'))).toBe(false);
});
it.each(['remove-directory', 'delete-directory'])('rejects stale, root, traversal, symlink and read-only %s without deleting data', async kind => {
  const command = { kind, path: 'notes/a/one', ...(kind === 'remove-directory' ? { destination: 'notes/a/two' } : {}) };
  const stale = (await list()).revision;
  write('notes/a/one/new.txt', 'new');
  expect((await post(command, stale)).status).toBe(409);
  for (const file of ['notes/a', 'notes/b', 'notes/a/../b', 'notes/a/one/../two']) expect((await post({ ...command, path: file })).status).toBe(400);
  fs.symlinkSync(path.join(root, 'notes/b'), path.join(root, 'notes/a/one/link'));
  expect((await post(command)).status).toBe(400);
  fs.unlinkSync(path.join(root, 'notes/a/one/link'));
  write('notes/a/one/AGENTS.md', 'protected');
  expect((await post(command)).status).toBe(400);
  fs.unlinkSync(path.join(root, 'notes/a/one/AGENTS.md'));
  git('checkout', '-b', 'readonly');
  expect((await post(command)).status).toBe(403);
  expect(fs.readFileSync(path.join(root, 'notes/a/one/note.md'), 'utf8')).toBe('# Note\n');
});
it.each(['unlinkSync', 'rmdirSync'] as const)('rolls recursive deletion back after %s fails, including original binary bytes and modes', failure => {
  write('notes/a/one/child/.hidden', 'private');
  fs.chmodSync(path.join(root, 'notes/a/one/child/.hidden'), 0o640);
  const command = { kind: 'delete-directory' as const, notebookId: 'a', path: 'notes/a/one' };
  const notebooks = loadWorkspaceConfig(root)!.notebooks;
  const before = localFileSnapshot(root, notebooks, command), after = planFileChange(before, command);
  const original = fs[failure].bind(fs);
  let calls = 0;
  vi.spyOn(fs, failure).mockImplementation((file: fs.PathLike) => {
    if (++calls === 2) throw new Error('Injected delete failure');
    return original(file);
  });
  expect(() => applyLocalFilePlan(root, before, after)).toThrow('Injected delete failure');
  expect(localFileSnapshot(root, notebooks, command)).toEqual(before);
  expect(fs.statSync(path.join(root, 'notes/a/one/child/.hidden')).mode & 0o777).toBe(0o640);
});
it('serializes concurrent destructive commands so only the first matching revision succeeds', async () => {
  const revision = (await list()).revision;
  const results = await Promise.all([post({ kind: 'delete-directory', path: 'notes/a/one' }, revision), post({ kind: 'delete-directory', path: 'notes/a/two' }, revision)]);
  expect(results.map(response => response.status).sort()).toEqual([200, 409]);
  expect([fs.existsSync(path.join(root, 'notes/a/one')), fs.existsSync(path.join(root, 'notes/a/two'))].filter(Boolean)).toHaveLength(1);
});
it('browses large binary files without loading their contents and reports the read limit separately', async () => {
  write('notes/a/large.bin', Buffer.alloc(6 * 1024 * 1024));
  const listing = await list();
  expect(listing.entries.find((entry: any) => entry.path === 'notes/a/large.bin').size).toBe(6 * 1024 * 1024);
  const assets = await fetch(base + '/api/assets?notebookId=a');
  expect(assets.status).toBe(200);
  expect((await assets.json()).assets.find((entry: any) => entry.path === 'notes/a/large.bin').size).toBe(6 * 1024 * 1024);
  expect((await fetch(base + '/api/files/read?notebookId=a&path=notes/a/large.bin')).status).toBe(413);
  expect((await post({ kind: 'write', path: 'notes/a/.hidden.json', content: '{"saved":true}\n' })).status).toBe(200);
  expect(fs.statSync(path.join(root, 'notes/a/large.bin')).size).toBe(6 * 1024 * 1024);
  expect((await post({ kind: 'move', path: 'notes/a/one/note.md', destination: 'notes/a/two/note.md' })).status).toBe(200);
  expect(fs.statSync(path.join(root, 'notes/a/large.bin')).size).toBe(6 * 1024 * 1024);
});
it('moves outline sources, targets and folders through HTTP while stale edits and deletion preserve references', async () => {
  const original = '- Parent\r\n  Annotation\r\n  - [Note\\] 中文](one/note.md#part)\r\n';
  write('notes/a/plan.outline.md', original);
  write('notes/a/ref.md', '[Plan](plan.outline.md)\n');
  write('notes/b/plan.outline.md', original);
  const stale = (await list()).revision;
  write('notes/a/plan.outline.md', original + '- Concurrent edit\r\n');
  expect((await post({ kind: 'move', path: 'notes/a/one/note.md', destination: 'notes/a/two/note.md' }, stale)).status).toBe(409);
  expect(fs.existsSync(path.join(root, 'notes/a/one/note.md'))).toBe(true);
  expect((await post({ kind: 'move', path: 'notes/a/one/note.md', destination: 'notes/a/two/note.md' })).status).toBe(200);
  expect((await post({ kind: 'move', path: 'notes/a/plan.outline.md', destination: 'notes/a/one/plan.outline.md' })).status).toBe(200);
  expect(fs.readFileSync(path.join(root, 'notes/a/one/plan.outline.md'), 'utf8')).toBe(original.replace('(one/note.md#part)', '(../two/note.md#part)') + '- Concurrent edit\r\n');
  expect((await post({ kind: 'move', path: 'notes/a/one', destination: 'notes/a/two/one' })).status).toBe(200);
  const final = original.replace('(one/note.md#part)', '(../note.md#part)') + '- Concurrent edit\r\n';
  expect(fs.readFileSync(path.join(root, 'notes/a/two/one/plan.outline.md'), 'utf8')).toBe(final);
  expect(fs.readFileSync(path.join(root, 'notes/a/ref.md'), 'utf8')).toBe('[Plan](two/one/plan.outline.md)\n');
  expect((await post({ kind: 'delete', path: 'notes/a/two/note.md' })).status).toBe(200);
  expect(fs.readFileSync(path.join(root, 'notes/a/two/one/plan.outline.md'), 'utf8')).toBe(final);
  expect(fs.readFileSync(path.join(root, 'notes/b/plan.outline.md'), 'utf8')).toBe(original);
  expect(git('log', '--format=%s').toString().trim()).toBe('fixture');
});
it('includes hidden files in the normal Git review and commit flow', async () => {
  await post({ kind: 'write', path: 'notes/a/.hidden.json', content: '{"a":2}\n' });
  const response = await fetch(base + '/api/git/diff?path=notes/a/.hidden.json');
  expect(response.status).toBe(200);
  expect((await response.json()).diff).toContain('"a":2');
  const { changes } = await fetch(base + '/api/git/changes').then(r => r.json());
  const change = changes.find((entry: any) => entry.path === 'notes/a/.hidden.json');
  expect(change.available).toBe(true);
  const committed = await fetch(base + '/api/git/commit-staged', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selected: true, files: [change.path], revisions: { [change.path]: change.revision }, message: 'Update hidden file' }) });
  expect(committed.status).toBe(200);
  expect(git('show', 'HEAD:notes/a/.hidden.json').toString()).toContain('"a":2');
});
